-- MySQL Script generated by MySQL Workbench
-- Wed Apr 16 10:18:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mercadinho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercadinho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercadinho` DEFAULT CHARACTER SET utf8 ;
USE `mercadinho` ;

-- -----------------------------------------------------
-- Table `mercadinho`.`Loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercadinho`.`Loja` ;

CREATE TABLE IF NOT EXISTS `mercadinho`.`Loja` (
  `Id_Loja` INT NOT NULL,
  `NmLoja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Loja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`Gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercadinho`.`Gerente` ;

CREATE TABLE IF NOT EXISTS `mercadinho`.`Gerente` (
  `Id_Geren` INT NOT NULL AUTO_INCREMENT,
  `Nm_Geren` VARCHAR(45) NOT NULL,
  `Id_Loja` INT NOT NULL,
  PRIMARY KEY (`Id_Geren`),
  INDEX `Id_Loja_idx` (`Id_Loja` ASC) VISIBLE,
  CONSTRAINT `Id_Loja`
    FOREIGN KEY (`Id_Loja`)
    REFERENCES `mercadinho`.`Loja` (`Id_Loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercadinho`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mercadinho`.`Funcionario` (
  `Id_Func` INT NOT NULL,
  `Id_Loja` INT NOT NULL,
  `Nm_Func` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Func`),
  INDEX `Id_Loja_F_idx` (`Id_Loja` ASC) VISIBLE,
  CONSTRAINT `Id_Loja_F`
    FOREIGN KEY (`Id_Loja`)
    REFERENCES `mercadinho`.`Loja` (`Id_Loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`Geladeira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercadinho`.`Geladeira` ;

CREATE TABLE IF NOT EXISTS `mercadinho`.`Geladeira` (
  `Id_Gelad` INT NOT NULL,
  `Id_Loja` INT NOT NULL,
  `Nm_Gelad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Gelad`),
  INDEX `Id_Loja_idx` (`Id_Loja` ASC) VISIBLE,
  CONSTRAINT `Id_Loja_Gela`
    FOREIGN KEY (`Id_Loja`)
    REFERENCES `mercadinho`.`Loja` (`Id_Loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`SensorPresenca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercadinho`.`SensorPresenca` ;

CREATE TABLE IF NOT EXISTS `mercadinho`.`SensorPresenca` (
  `Id_RegP` INT NOT NULL,
  `Dt_SenP` DATETIME NOT NULL,
  `Tm_SenP` INT NOT NULL,
  `Oc_Sens` TINYINT NOT NULL,
  `Id_Gelad` INT NOT NULL,
  `Id_SenP` INT NOT NULL,
  PRIMARY KEY (`Id_RegP`),
  INDEX `Id_Gelad_idx` (`Id_Gelad` ASC) VISIBLE,
  CONSTRAINT `Id_Gelad`
    FOREIGN KEY (`Id_Gelad`)
    REFERENCES `mercadinho`.`Geladeira` (`Id_Gelad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`SensorContato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercadinho`.`SensorContato` ;

CREATE TABLE IF NOT EXISTS `mercadinho`.`SensorContato` (
  `Id_RegC` INT NOT NULL,
  `Dt_SenC` DATETIME NOT NULL,
  `Tm_SenC` INT NOT NULL,
  `Ab_SenC` TINYINT NOT NULL,
  `Id_Gelad` INT NOT NULL,
  `Id_SenC` INT NOT NULL,
  PRIMARY KEY (`Id_RegC`),
  INDEX `Id_Gelad_idx` (`Id_Gelad` ASC) VISIBLE,
  CONSTRAINT `Id_Gelad_Cont`
    FOREIGN KEY (`Id_Gelad`)
    REFERENCES `mercadinho`.`Geladeira` (`Id_Gelad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`SensorPassagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mercadinho`.`SensorPassagem` ;

CREATE TABLE IF NOT EXISTS `mercadinho`.`SensorPassagem` (
  `Id_RegF` INT NOT NULL,
  `Dt_SenF` DATETIME NOT NULL,
  `En_SenF` INT NOT NULL,
  `Sd_SenF` INT NOT NULL,
  `Id_Loja` INT NOT NULL,
  `Id_SenF` INT NOT NULL,
  PRIMARY KEY (`Id_RegF`),
  INDEX `Id_Loja_idx` (`Id_Loja` ASC) VISIBLE,
  CONSTRAINT `Id_Loja_pass`
    FOREIGN KEY (`Id_Loja`)
    REFERENCES `mercadinho`.`Loja` (`Id_Loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `loja` --> Inserção de dados
-- -----------------------------------------------------
insert into loja values(1, 'Pequeno Francisco');

-- -----------------------------------------------------
-- Table `geladeira` --> Inserção de dados
-- -----------------------------------------------------

insert into geladeira values(1, 1, 'Tom e Jerrys');
insert into geladeira values(2, 1, 'Kibão');
insert into geladeira values(3, 1, 'Batche de Latche');